# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10)),
                ('employee_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=25)),
                ('department', models.CharField(choices=[('DTS', 'D.Technical Services'), ('DEGS', 'D. E-Govt'), ('DFA', 'D. Finance and Admin'), ('DPRD', 'Planning'), ('LEGAL', 'Legal')], default='DFA', max_length=5)),
                ('start_date', models.DateTimeField()),
            ],
        ),
    ]
