# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0002_auto_20170813_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
