# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerApp', '0003_auto_20170813_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='user',
            new_name='username',
        ),
    ]
